version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/guen3
    overwrite: yes
file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/run_new_container.sh
      timeout: 180
      runas: ec2-user
    - location: scripts/health_check.sh
      timeout: 180
      runas: ec2-user
    - location: scripts/switch_container.sh
      timeout: 180
      runas: ec2-user