name: CI

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Create application.properties
        run: |
          echo "${{ secrets.APPLICATION }}" | base64 --decode > ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_DEV }}" | base64 --decode > ./src/main/resources/application-dev.yml
          echo "${{ secrets.APPLICATION_OAUTH }}" | base64 --decode > ./src/main/resources/application-oauth.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build without Test in Gradle
        run: ./gradlew build -x test